// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestEncode_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewEncode()

	called := false
	cmd.CommandAction = func(c *Encode) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--hexEncodedInput")
	args = append(args, "--format")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.hexEncodedInput != true {
		t.Errorf("Expected hexEncodedInput to be true, got '%v'", cmd.hexEncodedInput)
	}
	if cmd.format != "test" {
		t.Errorf("Expected format to be 'test', got '%v'", cmd.format)
	}
}
